### ISSUE TITLE
Upgrade to 0.3 API

### ISSUE THREAD

**Issue by mcupak** [mcupak/beacon-python#1]
Once finalized.

**Comment by kozbo** [comment]
Hi @mcupak,

I have found this code quite helpful. I have used it as a beacon service for the GA4GH reference server with just adding a few hundred lines of code, so thanks for the great head start! I will publish it shortly but before I do I have a few questions:
1. I see that many of the communication data structures in the code do not line up directly with the schemas. Is that discrepancy reflected in this issue?
2. Where can I find a description of what the 0.3 API entails?

Thanks again,

-Kevin

**Comment by mcupak** [comment]
Hi @kozbo, that's great to hear! It's really just a simple example, but I'm glad it provided a good start and I'd definitely be interested in seeing an implementation on top of a reference server. As a matter of fact, me and @patmagee have been planning to implement something similar in Java (https://github.com/mcupak/beacon-adapters/issues/2).
1. The data structures line up with the 0.2 schema release (https://beacon-network.org/#/developers/api/beacon). The discrepancy is indeed reflected in this issue and the API will be aligned with [ga4gh/beacon-team](https://github.com/ga4gh/beacon-team/) once 0.3 schema is released.
2. The 0.3 API is being finalized and should be released soon. It will be very similar to the current develop branch in [ga4gh/beacon-team](https://github.com/ga4gh/beacon-team/) repository (https://github.com/ga4gh/beacon-team/blob/develop/src/main/resources/avro/beacon.avdl).

**Comment by kozbo** [comment]
Thanks for the pointers @mcupak. I will change my code over to track the 0.3 schemas as that will be closer to the final version than where I am now (and it looks like you have released it!)

I will let you know once I have posted the code.

**Comment by mcupak** [comment]
@kozbo That's correct, Beacon 0.3 has been released. Thanks!

**Comment by kozbo** [comment]
@mcupak I posted my code [here](https://github.com/kozbo/Beacon-on-GA4GH-API) I apologize in advance for beginner python code :-). I welcome your advice!

**Comment by mcupak** [comment]
Thanks @kozbo, both for sharing the implementation (I added it to the [Beacon Team wiki](https://github.com/ga4gh/beacon-team/wiki/Beacon-implementations)) and the pull request (I'll review it shortly).
